name = "ExpFamilyDistributions"
uuid = "ac7c78bc-e309-483d-b879-ab7fdbfc3919"
authors = ["Lucas Ondel <lucas.ondel@gmail.com>"]
version = "1.0.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CUDA = "2.6"
Distributions = "0.24"
PDMats = "0.10"
SpecialFunctions = "0.10"
julia = "1.6"
